---
- name: Add user and grant sudo privileges
  hosts: all
  become: yes  # Run as root (sudo) to modify users and groups
  tasks:
    - name: Create user ''
      user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash

    - name: Add 'user' user to the sudo group
      user:
        name: "{{ username }}"
        groups: sudo
        append: yes
      when: "'ubuntu' in group_names"
    - name: Add 'ansible' user to the wheel group RHEL
      user:
        name: "{{ username }}"
        groups: wheel
        append: yes
      when: "'RHEL' in group_names"
    - name: Set password for 'user' user 
      user:
        name: "{{ username }}"
        password: "{{ password }}"
        update_password: on_create
      when: ansible_password is defined
