---
- name: Add ansible user and grant sudo privileges
  hosts: all
  become: yes  # Run as root (sudo) to modify users and groups
  tasks:
    - name: Create user 'ansible'
      user:
        name: ansible
        state: present
        shell: /bin/bash

    - name: Add 'ansible' user to the sudo group
      user:
        name: ansible
        groups: sudo
        append: yes

    - name: Set password for 'ansible' user (optional)
      user:
        name: ansible
        password: "{{ '$6$KSOMC2LzK1W.NgeB$EQ0LbfsejOIizJxjrZfmoMw9azohc9rgA/1HF7/IdQEou7c6YWHm73wVPMZQG1C93ZEg5w6K5bvkCQTaCiAPN1' }}"
        update_password: on_create
      when: ansible_password is defined
