---
- name: Install Checkmk Agent
  hosts: all
  become: true
  vars:
    checkmk_server: "http://192.168.100.7/homelab/check_mk"
    deb_agent: "check-mk-agent_2.4.0b4-1_all.deb"
    rpm_agent: "check-mk-agent-2.4.0b4-1.noarch.rpm"
  handlers:
  - name: Reload Firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded
  tasks:
    - name: Install required packages for downloading
      package:
        name: curl
        state: present

    - name: Download Checkmk agent for Debian-based systems
      when: ansible_os_family == "Debian"
      get_url:
        url: "{{ checkmk_server }}/agents/{{ deb_agent }}"
        dest: "/tmp/{{ deb_agent }}"

    - name: Install Checkmk agent on Debian
      when: ansible_os_family == "Debian"
      apt:
        deb: "/tmp/{{ deb_agent }}"
        state: present

    - name: Download Checkmk agent for RedHat-based systems
      when: ansible_os_family == "RedHat"
      get_url:
        url: "{{ checkmk_server }}/agents/{{ rpm_agent }}"
        dest: "/tmp/{{ rpm_agent }}"

    - name: Import Checkmk GPG key
      when: ansible_os_family == "RedHat"
      rpm_key:
        state: present
        key: "https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg"
    - name: Open port firewalld
      when: ansible_os_family == "RedHat"
      ansible.posix.firewalld:
        port: 6566/tcp
        permanent: yes
        state: enabled
        immediate: yes
      notify: Reload Firewalld
    - name: Install Checkmk agent on RedHat
      when: ansible_os_family == "RedHat"
      yum:
        name: "/tmp/{{ rpm_agent }}"
        state: present
 
    - name: Add host to Checkmk via REST API
      uri:
        url: "http://192.168.100.7/homelab/check_mk/api/1.0/domain-types/host_config/collections/all" 
        method: POST
        headers:
          Accept: "application/json"
        user: "automat"
        password: "S4EqMt%dSnPXh1lV"
        force_basic_auth: yes
        body_format: json
        body:
          host_name: "{{ inventory_hostname }}"
          folder: "/"
          attributes:
            ipaddress: "{{ ansible_host }}"
        status_code: 200

    - name: Run service discovery in Checkmk
      uri:
        url: "http://192.168.100.7/homelab/check_mk/api/1.0/domain-types/service_discovery_run/actions/start/invoke"
        method: POST
        user: "automat"
        password: "S4EqMt%dSnPXh1lV"
        force_basic_auth: yes
        headers:
          Accept: "application/json"
        body_format: json
        body:
          host_name: "{{ inventory_hostname }}"
          mode: "refresh"
        status_code: [200,303]
      register: discovery_result

    - name: Wait for service discovery completion
      uri:
        url: "http://192.168.100.7/homelab/check_mk/api/1.0/objects/service_discovery_run/{{ inventory_hostname }}/actions/wait-for-completion/invoke"
        method: GET
        user: "automat"
        password: "S4EqMt%dSnPXh1lV"
        force_basic_auth: yes
        headers:
          Accept: "application/json"
        status_code: [200, 204]
      register: completion_result

    - name: Activate pending changes in Checkmk
      uri:
        url: "http://192.168.100.7/homelab/check_mk/api/1.0/domain-types/activation_run/actions/activate-changes/invoke"
        method: POST
        user: "automat"
        password: "S4EqMt%dSnPXh1lV"
        force_basic_auth: yes
        headers:
          Accept: "application/json"
        body_format: json
        body:
          force_foreign_changes: "true"
          sites: ["homelab"]
          redirect: "false"
        status_code: [200, 303, 428]
