---
- name: Sync scripts from NFS to all Debian servers
  hosts: all  # You can target all hosts here
  become: yes
  vars:
    nfs_server: "192.168.100.4"
  tasks:
    - name: install nfs tools
      when: ansible_os_family == "RedHat"
      apt:
        name: nfs-kernel-server
        state: present
    - name: Mount the NFS share
      ansible.builtin.mount:
        path: /mnt/tmp
        src: "{{ nfs_server }}:/mnt/WDRed-pool/orzech"
        fstype: nfs
        state: mounted
      when: ansible_facts['os_family'] == 'Debian'
      # This task will only run on hosts where the OS family is Debian.

    - name: Synchronize scripts from NFS to /usr/lib/check_mk_agent/local/
      ansible.builtin.synchronize:
        src: "/mnt/orzech/linux/cmk-scripts/"
        dest: "/usr/lib/check_mk_agent/local/"
        mode: '0777'
        recursive: yes
        owner: yes
        group: yes
        perms: yes
        delete: no
      when: ansible_facts['os_family'] == 'Debian'
      # This task will only run on hosts where the OS family is Debian.

    - name: Unmount NFS share
      ansible.builtin.mount:
        path: /mnt/tmp
        state: absent
      when: ansible_facts['os_family'] == 'Debian'
      # This task will only run on hosts where the OS family is Debian.
